# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='pub_data',
            new_name='pub_date',
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
