# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20170523_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='title',
            field=models.CharField(default='No title', max_length=50),
        ),
        migrations.AlterField(
            model_name='goal',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
