# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20170528_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='title',
            field=models.TextField(default='No title', max_length=50),
        ),
    ]
