# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20170530_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='records',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
