# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20170530_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='pub_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='pub_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
